version: "3.8"
services:
  m-s-server:
    build: ./server
    container_name: m-s-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

  loki:
    image: grafana/loki:2.8.2
    container_name: m-s-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.8.2
    container_name: m-s-promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.2
    container_name: m-s-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: unless-stopped
